### PR TITLE
fix: removed sealed keyword from FakeCosmos

### PR DESCRIPTION
**Pull request by egil**
Removing the `sealed` keyword makes it possible to create specialized versions, that implement custom interfaces.

For example:

If we have the following types:

1. `public class Group : CosmosResource` type.
2. `IGroupReader : ICosmosReader<Group>` that contain additional methods that simplify querying a Cosmos container, e.g. 

```c#
public interface IGroupReader : ICosmosReader<Group>
{
    public Task<Group?> FindByIdAsync(string groupId, CancellationToken cancellationToken)
        => FindAsync(groupId, Names.GroupPartitionKey, cancellationToken);
}
```

3. A system under test, `CanHazGroup` that uses `IGroupReader`

Then we're able to create a custom fake to use with AutoFixture and NSubsitute:

```c#
public class FakeGroupCosmos : FakeCosmos<Group>, IGroupReader { }
```

Like so:

```c#
[Theory, AutoNSubstituteData]
internal async Task RetrieveGroupById_with_existing_groupId(
    [Frozen(Matching.ImplementedInterfaces)] FakeGroupCosmos cosmos,
    CosmosGroupRepository sut,
    Group group)
{
    cosmos.Documents.Add(group);

    //...
}
```

Using interfaces like `IGroupReader` instead of directly `ICosmosReader` allows me to keep details like partition keys internal to the library that implements cosmos access.

### CODE REVIEW

**Comment by rickykaare** [comment]
I do not understand why you would make IGroupReader inherit from ICosmosReader<Group>. That would expose all the ICosmosReader functionallity you are trying to hide, and it won’t work out of the box with the registered CosmosReader. 
Wouldn’t it be better to have the IGroupReader implementation use the ICosmosReader<Group> ?

**Comment by rickykaare** [comment]
No, the `FakeCosmos` only works with the `ICosmosReader` and `ICosmosWriter` types (including the bulk variations). 

I don't really see why you would implement your own version of any of these types as this is basically the functionallity of Atc.Cosmos you are replacing. 

I would recommend using composition over inheritance, and create a `GroupReader` that takes an `ICosmosReader<Group>` in via constructor injection. The `GroupReader` is a perfect place to hide internal Cosmos details like partition keys, special queries etc. 

This would be easy to unit test using NSubstitute+AutoFixture and many examples exists on that. 

For broader scoped tests (e.g. Integration Tests) you could use the FakeCosmos implementation instead of the real database. In an AutoNSubstituteData setup you would need to freeze the FakeCosmos by ImplementedInterfaces before your GroupReader is declared.

**Comment by egil** [comment]
> No, the `FakeCosmos` only works with the `ICosmosReader` and `ICosmosWriter` types (including the bulk variations). 
> 
> I don't really see why you would implement your own version of any of these types as this is basically the functionallity of Atc.Cosmos you are replacing. 

Agreed. Not what I'm doing either 🙂

> I would recommend using composition over inheritance, and create a `GroupReader` that takes an `ICosmosReader<Group>` in via constructor injection. The `GroupReader` is a perfect place to hide internal Cosmos details like partition keys, special queries etc. 

This is what in doing 🙂

> This would be easy to unit test using NSubstitute+AutoFixture and many examples exists on that. 
> 
> For broader scoped tests (e.g. Integration Tests) you could use the FakeCosmos implementation instead of the real database. In an AutoNSubstituteData setup you would need to freeze the FakeCosmos by ImplementedInterfaces before your GroupReader is declared. 

So in my test method, it should receive first the FakeCosmos type and then my GroupReader, both Frozen.

Ok, I'll try again, didn't get that working yesterday.

**Comment by rickykaare** [comment]
Example here: https://github.com/atc-net/atc-cosmos/blob/89d972294a7f2ea4fb9eeedbea9ccfe059eb3922/test/Atc.Cosmos.Tests/Testing/FakeCosmosTests.cs#L35

**Comment by egil** [comment]
I think my case is slightly different.

I have `GroupReader : IGroupReader` which takes an `ICosmosReader<Group>` as input in it's ctor.

My SUT in my test is a `GroupEndpointHandler`, that takes a `IGroupReader` as input in it's ctor.

But I think I'll just need something like this:

```c#
public void Mytest(
[Frozen(Matching.ImplementedInterfaces)] FakeCosmos<Record> cosmos,
[Frozen(Matching.ImplementedInterfaces)] GroupReader reader,
GroupEndpointHandler sut)
```

But will have to check once the kids are out of my hair.

**Pull request closed without merging**
